In [180]:
''' 
Currently following TensorFlow from the ground up.

Key points
- While you don't need Python to use TensorFlow, you almost always build your models and do training using Python
- The arc of machine learning is:
    Collect data -> Represent the weights (Parameters) -> Build our model out of groups of weights -> Train those weights -> Accelerate the training

- Tensorflow Layers

        TF Probability TFX,
            |   |
        Keras   Sonet   
            |   |
            TF Graph
        Eager   Compilation
            |   |
            Runtime

             |  |
            Kernels

5 Key pieces to keep in mind when using TensorFlow
    1.  Tensors - Used to represent data
        a. These are also strongly typed. eg.
            floats, ints, boleans, strings, sparse, ragged, etc.
        b. They are immutable, as in, unable to update them but will create a new one
        c. Everything is turned to a tensor. Images, sounds, text, etc.
        d. They are also fast, can be vectorized and used on accelerators
        e. It has a shape
        f. Has axes or dimensions 
        g. Has a size
    2.  Variables - used to represent weights
        1. A variables acts and looks like a tensor
    3.  Modules - Used to build the models
    4.  Gradients tapes - Used to train the model
        1. Automatic differentation
        2. To do machine learning, you have to take a lot of gradients
        3. Records per operation gradient functions
        4. Only records the computation that actually took place
        5. Can watch any variables
    5.  tf.function - Usedto accelrate the training
    
References:
https://youtu.be/3LLZzi48iB8
'''

" \nCurrently following TensorFlow from the ground up.\n\nKey points\n- While you don't need Python to use TensorFlow, you almost always build your models and do training using Python\n- The arc of machine learning is:\n    Collect data -> Represent the weights (Parameters) -> Build our model out of groups of weights -> Train those weights -> Accelerate the training\n\n- Tensorflow Layers\n\n        TF Probability TFX,\n            |   |\n        Keras   Sonet   \n            |   |\n            TF Graph\n        Eager   Compilation\n            |   |\n            Runtime\n\n             |  |\n            Kernels\n\n5 Key pieces to keep in mind when using TensorFlow\n    1.  Tensors - Used to represent data\n        a. These are also strongly typed. eg.\n            floats, ints, boleans, strings, sparse, ragged, etc.\n        b. They are immutable, as in, unable to update them but will create a new one\n        c. Everything is turned to a tensor. Images, sounds, text, etc.\n        d.

In [1]:
# import tensorflow library
import tensorflow as tf

In [43]:
# Get a list of tensorflow devices
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [3]:
# Closer look at tensors
# Create a float tensor with a scalar
# Basically a rank 0 tensor
#This has a dtype of float32
tf.constant(10.0)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [4]:
#This has a dtype of int
# Same here. Rank 0 or scalar.
tf.constant(10)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [6]:
# Looking at a rank 1 tensor of dtype float32.
tf.constant([10.5, 4.6])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.5,  4.6], dtype=float32)>

In [11]:
# A more complext tensor
tf.complex(tf.constant([4.1,5.2,6.3]), tf.constant([7.3,8.2,9.1]))

<tf.Tensor: shape=(3,), dtype=complex64, numpy=array([4.1+7.3j, 5.2+8.2j, 6.3+9.1j], dtype=complex64)>

In [16]:
# create a string rank 2 tensor
tf.constant([['mangoes', 'star apples'], ['guava', 'cherries'], ['securitynik', 'Test']])

<tf.Tensor: shape=(3, 2), dtype=string, numpy=
array([[b'mangoes', b'star apples'],
       [b'guava', b'cherries'],
       [b'securitynik', b'Test']], dtype=object)>

In [20]:
# Looking at a rank 4 tensor
# This will have 3 batches of width 2 with 4 rows and 5 columns
rank_4_tensor = tf.zeros(shape=(3,2,4,5), dtype='int32')
rank_4_tensor

<tf.Tensor: shape=(3, 2, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]])>

In [21]:
# Get the type of elements in rank_4_tensor
rank_4_tensor.dtype

tf.int32

In [22]:
# Get the number of dimensions in rank_4_tensor
rank_4_tensor.ndim


4

In [23]:
# Get the shape of the rank_4_tensor
rank_4_tensor.shape

TensorShape([3, 2, 4, 5])

In [27]:
# Get the total number of elements in the rank_4_tensor
# This will be 3*2*4*5
tf.size(rank_4_tensor).numpy()

120

In [29]:
# Working with TFVariables
tf.constant([[2,3,4], [5,6,7]], dtype='float32')

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>

In [30]:
# The variable and the constant looks much the same
tf.Variable(tf.constant([[2,3,4], [5,6,7]], dtype='float32'))

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[2., 3., 4.],
       [5., 6., 7.]], dtype=float32)>

In [34]:
# The different between a tensor and a variable is that the variable can be reassigned
new_variable = tf.Variable(tf.constant([[2,3,4]], dtype='float32'))
new_variable

<tf.Variable 'Variable:0' shape=(1, 3) dtype=float32, numpy=array([[2., 3., 4.]], dtype=float32)>

In [63]:
# Tell TensorFlow which device to use
with tf.device('CPU:0'):
    var_1 = tf.Variable([[1,2,3], [4,5,6]])
    var_2 = tf.Variable([[4,5,6], [7,8,9]])

    # perform an element wise calculation or get the Hadamar product
    print(f'Hadamard Product/Pairwise calculation: \n{ var_1 * var_2 }')


Hadamar Product/Pairwise calculation: 
[[ 4 10 18]
 [28 40 54]]


In [167]:
# performing math operation with Variables
x_data = tf.constant([2., 3., 4.], dtype=tf.float32)
weights = tf.Variable([1., 2., 3.], dtype=tf.float32)
bias = tf.Variable([2.0])

# Make a prediction via element wise / Hadamard product
y_hat = (x_data * weights) + bias
y_hat

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 4.,  8., 14.], dtype=float32)>

In [168]:
# Gradient tape

In [169]:
# create a variable x
x = tf.Variable([3, 3.], dtype=tf.float32)
x.numpy()

array([3., 3.], dtype=float32)

In [170]:
# Square x and store it in y
y = x**2
y.numpy()

array([9., 9.], dtype=float32)

In [171]:
# Or alternatively
tf.math.square(x).numpy()

array([9., 9.], dtype=float32)

In [172]:
# What is the derivative of y with respect to X
# Starting with gradient tape
with tf.GradientTape() as tape:
    y = x**2
    print(y)

tf.Tensor([9. 9.], shape=(2,), dtype=float32)


In [173]:
# Use the gradient tape to find the derivative of y with respect to x
dy_dx = tape.gradient(y, x)
dy_dx.numpy()

array([6., 6.], dtype=float32)

In [174]:
# From a different perspective, using a ML model
tf.keras.utils.set_random_seed(10)
layer = tf.keras.layers.Dense(units=2, activation='relu')
x = tf.constant([[1., 2., 3.]], dtype=tf.float32)
layer, x

(<keras.layers.core.dense.Dense at 0x151487d8c70>,
 <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 2., 3.]], dtype=float32)>)

In [175]:
# Taking a look to see what the output of the neurons are
layer(x)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[2.893621, 4.519438]], dtype=float32)>

In [176]:
# Leveraging the GradientTape()
with tf.GradientTape() as tape:
    # Do the forward pass
    y_hat = layer(x)
    print(f'Model predicted: {y_hat}')
    # Compute the loss
    loss = tf.reduce_mean(y_hat**2)
    print(f'Model loss: {loss}')


Model predicted: [[2.893621 4.519438]]
Model loss: 14.399179458618164


In [177]:
# Calculate the gradient with respect to the training variables
gradient = tape.gradient(loss, layer.trainable_variables)
gradient

[<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 2.893621,  4.519438],
        [ 5.787242,  9.038876],
        [ 8.680862, 13.558313]], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.893621, 4.519438], dtype=float32)>]

In [179]:
# Get information on the weights and biases
for var, g in zip(layer.trainable_variables, gradient):
    print(var.name, g.shape)

dense_22/kernel:0 (3, 2)
dense_22/bias:0 (2,)
