Author: Nik Alleyne <br>
Author Blog: **https://www.securitynik.com** <br>
Author GitHub: **github.com/securitynik** <br>

Author Books: [  <br>

                "https://www.amazon.ca/Learning-Practicing-Leveraging-Practical-Detection/dp/1731254458/", 
                
                "https://www.amazon.ca/Learning-Practicing-Mastering-Network-Forensics/dp/1775383024/" 
            ] 


### Why this series?
When teaching the SANS SEC595: Applied Data Science and Machine Learning for Cybersecurity Professionals 
**https://www.sans.org/cyber-security-courses/applied-data-science-machine-learning/** I am always asked,
"Will you be sharing your demo notebooks?" or "Can we get a copy of your demo notebooks?" or ... well you get the point.
My answer is always no. Not that I do not want to share, (sharing is caring :-D) , but the demo notebooks 
by themselves, would not make sense or add real value. Hence, this series! 

This is my supplemental work, similar to what I would do in the demos but with a lot more details and references.

## 02 - Beginning Tensorflow

### The series includes the following: <br>
01 - Beginning Numpy <br>
02 - Beginning Tensorflow  <br>
03 - Beginning PyTorch <br>
04 - Beginning Pandas <br>
05 - Beginning Matplotlib <br>
06 - Beginning Data Scaling <br>
07 - Beginning Principal Component Analysis (PCA) <br>
08 - Beginning Machine Learning Anomaly Detection - Isolation Forest and Local Outlier Factor <br>
09 - Beginning Unsupervised Machine Learning - Clustering - K-means and DBSCAN <br>
10 - Beginning Supervise Learning - Machine Learning - Logistic Regression, Decision Trees and Metrics <br>
11 - Beginning Linear Regression - Machine Learning <br>
12 - Beginning Deep Learning - Anomaly Detection with AutoEncoders, Tensorflow <br>
13 - Beginning Deep Learning - Anomaly Detection with AutoEncoders, PyTroch <br>
14 - Beginning Deep Learning - Linear Regression, Tensorflow <br>
15 - Beginning Deep Learning - Linear Regression, PyTorch <br>
16 - Beginning Deep Learning - Classification, Tensorflow <br>
17 - Beginning Deep Learning - Classification, Pytorch <br>
18 - Beginning Deep Learning - Classification - regression - MIMO - Functional API Tensorflow <br> 
19 - Beginning Deep Learning - Convolution Networks - Tensorflow <br>
20 - Beginning Deep Learning - Convolution Networks - PyTorch <br>
21 - Beginning Regularization - Early Stopping, Dropout, L2 (Ridge), L1 (Lasso) <br>
22 - Beginning Model TFServing <br>

But conn.log is not the only log file within Zeek. Let's build some models for DNS and HTTP logs. <br>
I choose unsupervised, because there are no labels coming with these data. <br>

23 - Continuing Anomaly Learning - Zeek DNS Log - Machine Learning <br>
24 - Continuing Unsupervised Learning - Zeek HTTP Log - Machine Learning <br>

This was a specific ask by someone in one of my class. <br>
25 - Beginning - Reading Executables and Building a Neural Network to make predictions on suspicious vs suspicious  <br><br>

With 25 notebooks in this series, it is quite possible there are things I could have or should have done differently.  <br>
If you find any thing, you think fits those criteria, drop me a line. <br>

If you find this series beneficial, I would greatly appreciate your feedback.


In [1]:
# Import the tensorflow library
import tensorflow as tf

In [2]:
# First up, get the version of tensorflow being used
tf.__version__

'2.12.0'

In [3]:
# Tensorflow is a deep learning framework
# While Numpy as seen in notebook 
#   01 - Beginning Numpy
# cannot be used with GPU, Tensorflow can.
# The system this notebook is being developed on does not have a GPU that is supported by Tensorflow
# Confirming the devices currently available and we see only CPU
tf.config.get_visible_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [4]:
# Looking at it a different way
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [5]:
# Take a look at the logical devices
# We see only CPU
tf.config.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU')]

In [6]:
# Setup an integer Tensor with 1 item
# In a constant the values cannot be changed
x = tf.constant(value=[10], name='tf_const')
x

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([10])>

In [7]:
# Above we see tf.Tensor, we can confirm this is the type
# We can confirm this is a Tensorflow Eager Tensor
type(x)

tensorflow.python.framework.ops.EagerTensor

In [8]:
# If you wanted to, you can get the value of x as a numpy array
x.numpy()

array([10])

In [9]:
# We can confirm this is a numpy array by looking at the type
# We can learn more numpy in 
#   01 - Beginning Numpy
type(x.numpy())

numpy.ndarray

In [10]:
# Setup Tensor with multiple integer items
# This time, transition to variable
# Values in variables can be changed. Think weight or bias vectors that are "trainable"
# Also assign x a name
x = tf.Variable(initial_value=[10, 20, 30], name='tf_variable_int')
x

<tf.Variable 'tf_variable_int:0' shape=(3,) dtype=int32, numpy=array([10, 20, 30])>

In [11]:
# Get the name of x
x.name

'tf_variable_int:0'

In [12]:
# Setup the tensor with multiple float variables
x = tf.Variable(initial_value=[10., 20., 30.], name='float_tensor')
x

<tf.Variable 'float_tensor:0' shape=(3,) dtype=float32, numpy=array([10., 20., 30.], dtype=float32)>

In [13]:
# Alternatively, cast the multiple item Tensor from integer to float
# Notice the dtype is float32
x =  tf.Variable(initial_value=[10, 20, 30], dtype=tf.float32, name='casted_from_int_to_float')
x

<tf.Variable 'casted_from_int_to_float:0' shape=(3,) dtype=float32, numpy=array([10., 20., 30.], dtype=float32)>

In [14]:
# Add a new dimension to the Tensor
# Make it a 2 dimension Tensor
# Notice the additional "[" and "]"
x = tf.Variable([[10, 20, 30]], dtype=tf.float32 )
x

<tf.Variable 'Variable:0' shape=(1, 3) dtype=float32, numpy=array([[10., 20., 30.]], dtype=float32)>

In [15]:
# Move the Tensor to 3 dimensions
# The output shape (1,1,3) tells us we have 1 group of 1x3.
x = tf.Variable([[[10, 20, 30]]], dtype=tf.float32, name='tf_float_variable' )
x

<tf.Variable 'tf_float_variable:0' shape=(1, 1, 3) dtype=float32, numpy=array([[[10., 20., 30.]]], dtype=float32)>

In [16]:
# Reshape the x tensor
# In this case, (-1, 1) means any amount of rows but only one column
# For this scenario, since x is 1 row and 3 columns, this transitions it to 3 rows and 1 column
# Notice the transition from 1 to 2 dimensions
x = tf.Variable([[[10, 20, 30]]], dtype=tf.float32, name='x_before_reshaped' )
x = tf.reshape(x, [-1, 1], name='x_reshaped')
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[10.],
       [20.],
       [30.]], dtype=float32)>

In [17]:
# Reshape the x tensor
# In this case, (1, -1) means only one row but any number of columns
# For this scenario, since x is 1 row and 3 columns, this remains 1 row and 3 columns
# Notice the transition from 1 to 2 dimensions
x = tf.Variable([[[10, 20, 30]]], dtype=tf.float32, name='x_before_reshaped' )
x = tf.reshape(x, [1, -1], name='x_reshaped')
x

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[10., 20., 30.]], dtype=float32)>

In [18]:
# Create two float tensors to stack
x = tf.Variable(initial_value=[1, 2, 3, 4, 5], dtype=tf.float32, name='x_before_stack')
y = tf.Variable(initial_value=[6, 7, 8, 9, 0], dtype=tf.float32, name='y_before_stack')

x, y

(<tf.Variable 'x_before_stack:0' shape=(5,) dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>,
 <tf.Variable 'y_before_stack:0' shape=(5,) dtype=float32, numpy=array([6., 7., 8., 9., 0.], dtype=float32)>)

In [19]:
# Stack x and y vertically
# Note this needs to be a list/array of items
# This is very helpful, if you would like to stack two datasets to create 1
# Maybe you have received new samples/observations
z = tf.stack([x, y], axis=0, name='vertical_stack_of_x_y')
z

<tf.Tensor: shape=(2, 5), dtype=float32, numpy=
array([[1., 2., 3., 4., 5.],
       [6., 7., 8., 9., 0.]], dtype=float32)>

In [20]:
# Concatenate horizontally
# This is helpful when you want to add new features to your dataset
# Notice I added another dimension to both x and y in the 'values'
# Remember this needs to be an array
# Notice the axis=1
z = tf.concat(values=[[x], [y]], axis=1, name='horizontal_stack_of+_x_y')
z

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[1., 2., 3., 4., 5., 6., 7., 8., 9., 0.]], dtype=float32)>

In [21]:
# Find the offset within x where the value equals 5
x = tf.Variable(initial_value=[10, 9, 8, 7, 6, 5, 4], dtype=tf.float32)
z = tf.where((x == 5))
z

<tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[5]], dtype=int64)>

In [22]:
# Confirming the return positioned within the Tensor
x[5]

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [23]:
# Generate a 4*4 Tensor of ones
tf.ones((4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [24]:
# Create a 6x6 Tensor with all zeros
x = tf.zeros([6,6], dtype=tf.float32)
x

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [25]:
# Update the item at position row 0 and column 0 with 2
# Counting for both the rows and columns start 0
# As a result, even though this Tensor is 6x6, you 
# will be going from 0 to 5 for the indexes
x = tf.tensor_scatter_nd_update(tensor=x, indices=[[0, 0]], updates=[2])
x


<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[2., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [26]:
# Update the items at position row 3, column 5 with 100
x = tf.tensor_scatter_nd_update(tensor=x, indices=[[3, 5]], updates=[100])
x

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[  2.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 100.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.]], dtype=float32)>

In [27]:
# Maybe instead, manipulate columns 1, 2 and 3 of the last row. 
# Remember, the last row is row 5
x = tf.tensor_scatter_nd_update(tensor=x, indices=[[5, 1], [5, 2], [5, 3], [5, 4]], updates=[23, 24, 25, 26])
x

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[  2.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 100.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  23.,  24.,  25.,  26.,   0.]], dtype=float32)>

In [28]:
# One more. Change the values from the last to the second column of row 2
# Giving them a value of -10
x = tf.tensor_scatter_nd_update(tensor=x, indices=[[1, 1], [1, 2], [1, 3], [1, 4]], \
                                updates=[-10, -10, -10, -10])
x

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[  2.,   0.,   0.,   0.,   0.,   0.],
       [  0., -10., -10., -10., -10.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 100.],
       [  0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,  23.,  24.,  25.,  26.,   0.]], dtype=float32)>

In [29]:
# Get the max value of all the items in the matrix
# Using two different strategies
tf.experimental.numpy.max(x), tf.reduce_max(input_tensor=x)

(<tf.Tensor: shape=(), dtype=float32, numpy=100.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=100.0>)

In [30]:
# Get the max value in the matrix going down the columns 
# Using two different strategies
# Going across axis=0
tf.experimental.numpy.max(x, axis=0), tf.reduce_max(input_tensor=x, axis=0)

(<tf.Tensor: shape=(6,), dtype=float32, numpy=array([  2.,  23.,  24.,  25.,  26., 100.], dtype=float32)>,
 <tf.Tensor: shape=(6,), dtype=float32, numpy=array([  2.,  23.,  24.,  25.,  26., 100.], dtype=float32)>)

In [31]:
# Get the max value in the matrix across each row
# Using two different strategies
tf.experimental.numpy.max(x, axis=1), tf.reduce_max(input_tensor=x, axis=1)

(<tf.Tensor: shape=(6,), dtype=float32, numpy=array([  2.,   0.,   0., 100.,   0.,  26.], dtype=float32)>,
 <tf.Tensor: shape=(6,), dtype=float32, numpy=array([  2.,   0.,   0., 100.,   0.,  26.], dtype=float32)>)

In [32]:
# Create an Tensor to be transposed
x = tf.Variable(initial_value=[[10, 9, 8, 7, 5]], dtype=tf.int32, name='tensor_before_transpose')
x

<tf.Variable 'tensor_before_transpose:0' shape=(1, 5) dtype=int32, numpy=array([[10,  9,  8,  7,  5]])>

In [33]:
# Use the full transpose function to change from a row vector to a column vector
x = tf.transpose(a=x, name='x_transpose')
x

<tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[10],
       [ 9],
       [ 8],
       [ 7],
       [ 5]])>

In [34]:
# Create a 4 * 4 eye matrix
# Notice all the ones on the diagonal
# This is helpful also when you think about one-hot encoding
x = tf.eye(num_rows=4, num_columns=4, dtype=tf.float32, name='eye_matrix')
x

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [35]:
# Preparing to do some math
# Define a Tensor with axes 0 and 1
x = tf.constant([[6,4,3], [9, 8, 0]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[6, 4, 3],
       [9, 8, 0]])>

In [36]:
# Get the sum of x
x_sum = tf.reduce_sum(x)
x_sum

<tf.Tensor: shape=(), dtype=int32, numpy=30>

In [37]:
# Rather than get the sum of the entire Tensor, 
# Get the sum of the rows, i.e axis=1
x_sum = tf.reduce_sum(x, axis=1)
x_sum

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([13, 17])>

In [38]:
# Similarly get the sum of the columns, i.e axis=0
x_sum = tf.reduce_sum(x, axis=0)
x_sum

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([15, 12,  3])>

In [39]:
# Get the average of the rows, axes=1
# Notice I had to cast x's datatype from integer to float
# if not, the returned average is an integer rather than a float
x_avg = tf.reduce_mean(tf.cast(x=x, dtype=tf.float32), axis=1)
x_avg

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.3333335, 5.6666665], dtype=float32)>

In [40]:
# Get the average of the rows, axes=1
# Notice I had to cast x's datatype from integer to float
# if not, the returned average is an integer rather than a float
x_avg = tf.reduce_mean(tf.cast(x=x, dtype=tf.float32), axis=0)
x_avg

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([7.5, 6. , 1.5], dtype=float32)>

In [41]:
# So I mentioned twice that I had to cast to get a float.
# If not, the output is an integer
# Let's try without casting to see what happens
# As you can see, we seem to have gotten the floor of the values
x_avg_without_cast = tf.reduce_mean(x, axis=0)
x_avg_without_cast

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([7, 6, 1])>

In [42]:
# Generate a random number between 10 and 20
# Because I would like a scalar output, the shape is empty
# At the same time, I would like an integer output, hence the dtype of tf.int32
tf.random.uniform(shape=[], minval=10, maxval=20, dtype=tf.int32).numpy()

11

In [43]:
# You may have instances you wish to generate the same random number
# Maybe for demonstration purposes. Like in this case.
# In this case, first set the random seed

for idx, item in enumerate(range(5)):
    # Set the random seed
    # Note, I'm using tf to set the seed. 
    # In the numpy notebook 
    #   01 - Beginning Numpy 
    # I set the seed using numpy
    tf.random.set_seed(10)
    
    # Generate the number
    print(f'Run: {idx} \t Num: {tf.random.uniform(shape=[], minval=10, maxval=20, dtype=tf.int32).numpy()}')

Run: 0 	 Num: 10
Run: 1 	 Num: 10
Run: 2 	 Num: 10
Run: 3 	 Num: 10
Run: 4 	 Num: 10


In [44]:
# In looking for max value within a Tensor, you might instead want the index of that value
# The value returned is 1. We can see 10 at index position 1
x = tf.Variable(initial_value=[2, 10, 5, 2, 3], dtype=tf.int32)
tf.argmax(x), x

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 2, 10,  5,  2,  3])>)

In [45]:
# Multiply two Tensors

# First create the matrices 
x = tf.constant(value=[[2,3,4]], dtype=tf.int32)
y = tf.constant(value=[[5],[4],[3]], dtype=tf.int32)
x, y

(<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[2, 3, 4]])>,
 <tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[5],
        [4],
        [3]])>)

In [46]:
# Getting the shape of the two Tensors
# to confirm their inner dimensions are the same
x.shape, y.shape

(TensorShape([1, 3]), TensorShape([3, 1]))

In [47]:
# Get the dot product of the two vectors
tf.tensordot(a=x, b=y, axes=1)

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[34]])>

In [48]:
# Alternatively, perform a pairwise or Hadamar product
tf.multiply(x=x, y=y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 15, 20],
       [ 8, 12, 16],
       [ 6,  9, 12]])>

In [49]:
# Prepare to get the cumulative sum of the x vector
x

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[2, 3, 4]])>

In [ ]:
# Get the cumulative sum of the Tensor
# Notice how the first value in x remains the same, then the first and second are added
# Then the second and third are added
tf.cumsum(x)

In [50]:
# Create x with 4 dimensions
# Especially needed when working with convolution networks
#   19 - Beginning Deep Learning, - Convolution Networks - Tensorflow
#   20 - Beginning Deep Learning, - Convolution Networks, PyTorch
x = tf.constant(value=[[[[2,3,4,5,6]]]])
x

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[2, 3, 4, 5, 6]]]])>

In [51]:
# Flatten x to a vector
# Especially needed when working with convolution networks and then need to transition to a dense layer
#   19 - Beginning Deep Learning, - Convolution Networks - Tensorflow
#   20 - Beginning Deep Learning, - Convolution Networks, PyTorch
tf.reshape(tensor=x, shape=[-1])

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6])>

In [52]:
# Alternatively, we could have used tf.experimental.numpy.ravel() to get a 1D array
x, tf.experimental.numpy.ravel(x)

(<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[2, 3, 4, 5, 6]]]])>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6])>)

In [53]:
# Create a 3*2 matrix
x = tf.Variable([[3,4,5], [6,7,8]])
x

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[3, 4, 5],
       [6, 7, 8]])>

In [54]:
# One more before moving on, broadcasting
# Taking a 2x3 matrix and multiple by a 1*3 vector
# https://numpy.org/doc/stable/user/basics.broadcasting.html
tf.multiply(tf.constant(value=[[10,2,3], [2,1,3]]), tf.constant(value=[4,5,6]))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[40, 10, 18],
       [ 8,  5, 18]])>

In [55]:
# The above is the same as multiplying 
# [[10,2,3],   * [[4,5,6]
# [2,1,3]]        [4,5,6]]
tf.multiply(tf.Variable(initial_value=[[10,2,3], [2,1,3]]), tf.Variable(initial_value=[[4,5,6], [4,5,6]]))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[40, 10, 18],
       [ 8,  5, 18]])>

In [56]:
# While I typically will use Pandas to read in data,
#   04 - Beginning Pandas <br>
# You also have the opportunity to do so with numpy
# Maybe you want to read in content from a .csv file in batches. 
# In this case, batches of 256
# https://www.tensorflow.org/api_docs/python/tf/data/experimental/make_csv_dataset
next(tf.data.experimental.make_csv_dataset(file_pattern='conn.log', \
                                           header=True, batch_size=256, field_delim=',').as_numpy_iterator())


OrderedDict([('id.orig_h id.orig_p id.resp_h id.resp_p service duration orig_bytes resp_bytes orig_pkts orig_ip_bytes resp_pkts resp_ip_bytes',
              array([b'192.168.0.31\t58487\t192.168.0.4\t80\t-\t0.000065\t0\t0\t1\t52\t1\t40',
                     b'192.168.0.21\t53542\t192.168.0.4\t9200\t-\t0.000052\t0\t0\t1\t52\t1\t40',
                     b'192.168.0.10\t55424\t89.187.183.77\t8888\thttp\t0.058498\t208\t976\t6\t528\t5\t1244',
                     b'192.168.0.31\t59079\t192.168.0.4\t80\t-\t0.000071\t0\t0\t1\t52\t1\t40',
                     b'192.168.0.31\t58535\t192.168.0.4\t80\t-\t0.000051\t0\t0\t1\t52\t1\t40',
                     b'192.168.0.21\t53343\t192.168.0.4\t9200\t-\t0.000047\t0\t0\t1\t52\t1\t40',
                     b'192.168.0.10\t54632\t89.187.183.77\t8888\thttp\t0.055387\t208\t976\t6\t516\t6\t1296',
                     b'192.168.0.4\t27761\t192.168.0.4\t38478\t-\t-\t-\t-\t0\t0\t0\t0',
                     b'192.168.0.31\t58669\t192.168.0.4\t80\t-\t0.00011

Additional References and good reads/videos <br>: <br>
https://www.tensorflow.org/guide/tensor <br>
https://medium.com/@schartz/the-shape-of-tensor-bab75001d7bc <br>
https://towardsdatascience.com/how-to-replace-values-by-index-in-a-tensor-with-tensorflow-2-0-510994fe6c5f <br>
https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_update <br>
https://www.tensorflow.org/api_docs/python/tf/math/reduce_max <br>
https://www.tensorflow.org/api_docs/python/tf/eye <br>
https://pytorch.org/docs/stable/generated/torch.tensordot.html <br>
https://www.tensorflow.org/guide/tensor <br>
https://www.tensorflow.org/api_docs/python/tf/keras/utils/text_dataset_from_directory <br>