Author: Nik Alleyne <br>
Author Blog: **https://www.securitynik.com** <br>
Author GitHub: **github.com/securitynik** <br>

Author Books: [  <br>

                "https://www.amazon.ca/Learning-Practicing-Leveraging-Practical-Detection/dp/1731254458/", 
                
                "https://www.amazon.ca/Learning-Practicing-Mastering-Network-Forensics/dp/1775383024/" 
            ] 

### Why this series?
When teaching the SANS SEC595: Applied Data Science and Machine Learning for Cybersecurity Professionals 
**https://www.sans.org/cyber-security-courses/applied-data-science-machine-learning/** I am always asked,
"Will you be sharing your demo notebooks?" or "Can we get a copy of your demo notebooks?" or ... well you get the point.
My answer is always no. Not that I do not want to share, (sharing is caring :-D) , but the demo notebooks 
by themselves, would not make sense or add real value. Hence, this series! 

This is my supplemental work, similar to what I would do in the demos but with a lot more details and references.

## 22. Beginning Model TFServing

### The series includes the following: <br>
01 - Beginning Numpy <br>
02 - Beginning Tensorflow  <br>
03 - Beginning PyTorch <br>
04 - Beginning Pandas <br>
05 - Beginning Matplotlib <br>
06 - Beginning Data Scaling <br>
07 - Beginning Principal Component Analysis (PCA) <br>
08 - Beginning Machine Learning Anomaly Detection - Isolation Forest and Local Outlier Factor <br>
09 - Beginning Unsupervised Machine Learning - Clustering - K-means and DBSCAN <br>
10 - Beginning Supervise Learning - Machine Learning - Logistic Regression, Decision Trees and Metrics <br>
11 - Beginning Linear Regression - Machine Learning <br>
12 - Beginning Deep Learning - Anomaly Detection with AutoEncoders, Tensorflow <br>
13 - Beginning Deep Learning - Anomaly Detection with AutoEncoders, PyTroch <br>
14 - Beginning Deep Learning - Linear Regression, Tensorflow <br>
15 - Beginning Deep Learning - Linear Regression, PyTorch <br>
16 - Beginning Deep Learning - Classification, Tensorflow <br>
17 - Beginning Deep Learning - Classification, Pytorch <br>
18 - Beginning Deep Learning - Classification - regression - MIMO - Functional API Tensorflow <br> 
19 - Beginning Deep Learning - Convolution Networks - Tensorflow <br>
20 - Beginning Deep Learning - Convolution Networks - PyTorch <br>
21 - Beginning Regularization - Early Stopping, Dropout, L2 (Ridge), L1 (Lasso) <br>
22 - Beginning Model TFServing <br>

But conn.log is not the only log file within Zeek. Let's build some models for DNS and HTTP logs. <br>
I choose unsupervised, because there are no labels coming with these data. <br>

23 - Continuing Anomaly Learning - Zeek DNS Log - Machine Learning <br>
24 - Continuing Unsupervised Learning - Zeek HTTP Log - Machine Learning <br>

This was a specific ask by someone in one of my class. <br>
25 - Beginning - Reading Executables and Building a Neural Network to make predictions on suspicious vs suspicious  <br><br>

With 25 notebooks in this series, it is quite possible there are things I could have or should have done differently.  <br>
If you find any thing, you think fits those criteria, drop me a line. <br>

If you find this series beneficial, I would greatly appreciate your feedback.


As we went through the notebooks above, we built a number of models. <br>
Now that we have built those models, how do we use them?  <br>
Well realistically, we already saw in almost all of the notebooks above,  <br>
how we can save the model to disk and reload to make predictions. <br> 

Let's try something different. Time to take advantage of Tensorflow serving <br> 

I'm running Ubuntu on Windows Subsystem for Linux <br> <br>

securitynik@SECURITYNIK-SURFACE:/Beginning_ML$ lsb_release --all <br> <br>
No LSB modules are available. <br>
Distributor ID: Ubuntu <br>
Description:    Ubuntu 22.04.2 LTS <br>
Release:        22.04 <br>
Codename:       jammy <br> <br>

My Docker version <br>
securitynik@SECURITYNIK-SURFACE:/Beginning_ML$ docker --version <br>
Docker version 23.0.2, build 569dd73 <br>

### Install Tensorflow Serving on Ubuntu

securitynik@SECURITYNIK-SURFACE:/Beginning_ML$ sudo docker pull tensorflow/serving <br>
[sudo] password for securitynik: <br>
Using default tag: latest <br>
latest: Pulling from tensorflow/serving <br>
ca1778b69356: Pull complete <br>
bbb7c3e24bc6: Pull complete <br>
c4f0a754ad10: Pull complete <br>
74ed73ecd97e: Pull complete <br>
a7597062a8f3: Pull complete <br>
Digest: sha256:d3ddbce3278e428f2ea960ccece77ad58fa9f5e74d4c5320f031fdb85b4519c1 <br>
Status: Downloaded newer image for tensorflow/serving:latest <br>
docker.io/tensorflow/serving:latest <br>

### With Tensorflow Serving installed, install the sample image <br>

securitynik@SECURITYNIK-SURFACE:~$ git clone https://github.com/tensorflow/serving <br>
Cloning into 'serving'... <br>
remote: Enumerating objects: 32871, done. <br>
remote: Counting objects: 100% (142/142), done. <br>
remote: Compressing objects: 100% (82/82), done. <br>
remote: Total 32871 (delta 60), reused 120 (delta 53), pack-reused 32729 <br>
Receiving objects: 100% (32871/32871), 18.07 MiB | 15.75 MiB/s, done. <br>
Resolving deltas: 100% (26363/26363), done. <br>

### Load up docker with the test image <br>

securitynik@SECURITYNIK-SURFACE:~$  docker run --tty --interactive  --rm --publish 8501:8501 --volume "./serving/tensorflow_serving/servables/tensorflow/testdata/saved_model_half_plus_two_cpu:/models/half_plus_two" --env MODEL_NAME=half_plus_two tensorflow/serving <br>
...
2023-05-05 03:07:36.277473: I tensorflow_serving/core/loader_harness.cc:95] Successfully loaded servable version {name: half_plus_two version: 123} <br>
... <br>
2023-05-05 03:07:36.281594: I tensorflow_serving/model_servers/server.cc:409] Running gRPC ModelServer at 0.0.0.0:8500 ...
[warn] getaddrinfo: address family for nodename not supported <br>
2023-05-05 03:07:36.287003: I tensorflow_serving/model_servers/server.cc:430] Exporting HTTP/REST API at:localhost:8501 ...
[evhttp_server.cc : 245] NET_LOG: Entering the event loop ... <br>


https://www.tensorflow.org/tfx/serving/docker <br>

### Test a prediction using curl <br>
securitynik@SECURITYNIK-SURFACE:~$  **curl -data '{"instances" : [1.0, 2.0, 5.0]}' --request POST http://172.17.0.1:8501/v1/models/half_plus_two:predict** <br>
{ <br>
    "predictions": [2.5, 3.0, 4.5 <br>
    ] <br>

### Test a prediction with Powershell <br>
PS C:\Users\SecurityNik> **Invoke-WebRequest -Uri "http://172.19.64.79:8501/v1/models/half_plus_two:predict" -Method POST -Body '{"instances" : [1.0, 2.0, 5.0]}' | Select-Object -ExpandProperty Content** <br>
{ <br>
    "predictions": [2.5, 3.0, 4.5 <br>
    ] <br>
} <br>

Now that we are aware how to use Tensorflow Serving, time to load our own model rather than the test. <br>
Let's use the autoencoder which was built in notebook: <br>
    12. Beginning Deep Learning - Anomaly Detection with AutoEncoders, Tensorflow <br>

Interestingly my current directory structure for the model we will use, looks like.  <br>
 <br>
├───TF_AUTOENCODER <br>
│   └───tf_autoencoder.tf <br>
│       ├───assets <br>
│       └───variables <br>
 <br>
However, we need to add some version information, so create a directory "1" under "tf_autoencoder.tf" and move the files into it <br>
 <br>
├───TF_AUTOENCODER <br>
│   └───tf_autoencoder.tf <br>
│       └───1 <br>
│           ├───assets <br>
│           └───variables <br>

Loading the autoencoder model <br>
 <br>
securitynik@SECURITYNIK-SURFACE:~$ **docker run --tty --interactive  --rm --publish 8501:8501 --volume "/mnt/d/ML/BeginningML/SAVED_MODELS/TF_AUTOENCODER/tf_autoencoder.tf/:/models/tf_autoencoder" --env MODEL_NAME=tf_autoencoder tensorflow/serving** <br> <br>
...
...
2023-05-28 17:28:20.737027: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:215] Running initialization op on SavedModel bundle at path: /models/tf_autoencoder/1 <br>
2023-05-28 17:28:20.754434: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:314] SavedModel load for tags { serve }; Status: success: OK. Took 217682 microseconds. <br>
...
2023-05-28 17:28:20.983646: I tensorflow_serving/core/loader_harness.cc:95] Successfully loaded servable version {name: tf_autoencoder version: 1} <br>
2023-05-28 17:28:20.988505: I tensorflow_serving/model_servers/server_core.cc:486] Finished adding/updating models <br>
2023-05-28 17:28:20.988650: I tensorflow_serving/model_servers/server.cc:118] Using InsecureServerCredentials <br>
2023-05-28 17:28:20.988678: I tensorflow_serving/model_servers/server.cc:383] Profiler service is enabled <br>
2023-05-28 17:28:20.989675: I tensorflow_serving/model_servers/server.cc:409] Running gRPC ModelServer at 0.0.0.0:8500 ...
[warn] getaddrinfo: address family for nodename not supported <br>
2023-05-28 17:28:20.995707: I tensorflow_serving/model_servers/server.cc:430] Exporting HTTP/REST API at:localhost:8501 ...
[evhttp_server.cc : 245] NET_LOG: Entering the event loop ... <br> <br>

With the service successfully loaded, we can now go about sending data to our model.  <br>

Make a prediction with curl <br>
securitynik@SECURITYNIK-SURFACE:~$ **curl --data '{"instances" : [[141.0, 356138566.0, 11037090.0, 60.0, 3026679.0, 33.0, 982584.0]]}' --request POST http://172.17.0.1:8501/v1/models/tf_autoencoder:predict** <br>
{ <br>
    "**predictions": [[3.53547932e-07, 5.11308649e-08, 1.05425784e-08, 3.68306837e-06, 3.3058825e-07, 1.75808657e-06, 1.29566089e-07]** <br>
    ] <br>
} <br>

Make prediction with Powershell <br>
 <br>
PS D:\> **Invoke-WebRequest -Uri "http://172.19.64.79:8501/v1/models/tf_autoencoder:predict" -Method POST -Body '{"instances" :  [[141.0, 356138566.0, 11037090.0, 60.0, 3026679.0, 33.0, 982584.0]]}' | Select-Object -ExpandProperty Content**   <br>                                                                                                                                             <br>{
    "**predictions": [[3.53547932e-07, 5.11308649e-08, 1.05425784e-08, 3.68306837e-06, 3.3058825e-07, 1.75808657e-06, 1.29566089e-07]** <br>
    ] <br>
} <br>

While we were able to make predictions, this is not exactly what we wanted. <br>
We still need to calculate the Mean Absolute Error (MAE) for these predictions. <br>
Basically, the prediction alone above is not good enough for us. <br>
Let's address this shortcoming! <br>

In [10]:
# Import the needed libraries
import tensorflow as tf
import numpy as np
import pickle
import json

In [11]:
# Storing our sample as a variable
new_sample = np.array([141., 356138566,	11037090, 60, 3026679, 33, 982584], dtype=np.float32, ndmin=2)
new_sample

array([[1.4100000e+02, 3.5613856e+08, 1.1037090e+07, 6.0000000e+01,
        3.0266790e+06, 3.3000000e+01, 9.8258400e+05]], dtype=float32)

In [12]:
# Before making a prediction we need to scale the data as was done during the model training in 
#   12 - Beginning Deep Learning - Anomaly Detection with AutoEncoders, Tensorflow
#   13 - Beginning Deep Learning - Anomaly Detection with AutoEncoders, PyTroch <br>
#
#   https://machinelearningmastery.com/how-to-save-and-load-models-and-data-preparation-in-scikit-learn-for-later-use/
#   https://stackabuse.com/bytes/how-to-save-and-load-fit-scikit-learn-scalers/
# Load the scaler which was saved in the above notebook
min_max_scaler = pickle.load(file=open('tf_min_max_scaler.pkl', mode='rb'))
min_max_scaler

MinMaxScaler()

In [13]:
# With the scaler loaded, time to transform our sample
# Remember, we need to preprocess the test or any prediction data, the same way as we did with the training data
new_sample_scaled = min_max_scaler.transform(new_sample)
new_sample_scaled

array([[4.2334208e-03, 6.1739308e-01, 5.2606082e-03, 2.1844395e-04,
        1.3436210e-02, 5.7754605e-05, 1.6974034e-03]], dtype=float32)

In [14]:
# Setup the data in json format to be sent to the model for prediction
data = json.dumps({'instances' : new_sample_scaled.tolist() })
data

'{"instances": [[0.004233420826494694, 0.6173930764198303, 0.005260608159005642, 0.00021844395087100565, 0.013436210341751575, 5.775460522272624e-05, 0.0016974033787846565]]}'

In [15]:
# Let's now access our model which is being served via TFServing
# Previously, we used curl as well as Invoke-WebReqest
# Time to do things differently
import requests

In [16]:
# Define a header content-type as Javascript Object Notation (JSON)
headers = {'content-type' : 'application/json', 'user-agent' : 'securitynik'}
headers

{'content-type': 'application/json', 'user-agent': 'securitynik'}

In [17]:
# Make a request
#   https://keras.io/examples/keras_recipes/tf_serving/
#   
json_response = requests.post(url='http://172.19.64.79:8501/v1/models/tf_autoencoder:predict', \
                              headers=headers, data=data)

# Store the predictions
initial_predictions = json_response.json()['predictions']

# What does the predictions look like
initial_predictions

[[3.58950103e-07,
  5.13086675e-08,
  1.05235536e-08,
  3.69800182e-06,
  3.30785667e-07,
  1.75776813e-06,
  1.29550529e-07]]

In [18]:
# Define a threshold which was set during development of the model
#   12. Beginning Deep Learning - Anomaly Detection with AutoEncoders, Tensorflow
THRESHOLD = 2401097.2
THRESHOLD

2401097.2

In [19]:
# Now that's progress! With the predictions in place and the threshold defined, let's move forward
suspicious_or_not = tf.keras.losses.mae(y_true=new_sample, y_pred=initial_predictions)
suspicious_or_not

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([53026452.], dtype=float32)>

In [20]:
# Import datetime library
from datetime import datetime

In [21]:
# Write some code to trigger an alert when a sample's reconstruction error passes our threshold
f'{datetime.now()} - [!] ALERT ** SUSPICIOUS ACTIVITY ** Zeek conn.log entry Threshold Exceeded' \
    if suspicious_or_not > THRESHOLD  else "[**] Normal Traffic"

'2023-05-28 23:00:41.939407 - [!] ALERT ** SUSPICIOUS ACTIVITY ** Zeek conn.log entry Threshold Exceeded'

In [22]:
# So we got the sample being reported as suspicious 
# Time to move on!

Additional references: <br>
https://neptune.ai/blog/how-to-serve-machine-learning-models-with-tensorflow-serving-and-docker <br>
https://grpc.io/ <br>
https://cloud.google.com/blog/products/api-management/understanding-grpc-openapi-and-rest-and-when-to-use-them <br>
https://www.tensorflow.org/tfx/serving/serving_config <br>
https://neptune.ai/blog/how-to-serve-machine-learning-models-with-tensorflow-serving-and-docker <br>