Author: Nik Alleyne <br>
Author Blog: https://www.securitynik.com <br>
Author GitHub:github.com/securitynik <br>
Author Books: [  <br>
                "https://www.amazon.ca/Learning-Practicing-Leveraging-Practical-Detection/dp/1731254458/",  <br>
                "https://www.amazon.ca/Learning-Practicing-Mastering-Network-Forensics/dp/1775383024/" <br>
            ] <br>


## 03 - Beginning PyTorch

This post is part of my beginning machine learning series.  <br>
The series includes the following: <br>

01 - Beginning Numpy <br>
02 - Beginning Tensorflow  <br>
03 - Beginning PyTorch <br>
04 - Beginning Pandas <br>
05 - Beginning Matplotlib <br>
06 - Beginning Data Scaling <br>
07 - Beginning Principal Component Analysis (PCA) <br>
08 - Beginning Machine Learning Anomaly Detection - Isolation Forest and Local Outlier Factor <br>
09 - Beginning Unsupervised Machine Learning - Clustering - KMeans and DBSCAN <br>
10 - Beginning Supervise Learning - Machine Learning - Logistic Regression, Decision Trees and Metrics <br>
11 - Beginning Linear Regression - Machine Learning <br>
12 - Beginning Deep Learning - Anomaly Detection with AutoEncoders, Tensorflow <br>
13 - Beginning Deep Learning - Anomaly Detection with AutoEncoders, PyTroch <br>
14 - Beginning Deep Learning, - Linear Regression, Tensorflow <br>
15 - Beginning Deep Learning, - Linear Regression, PyTorch <br>
16 - Beginning Deep Learning, - Classification, Tensorflow <br>
17 - Beginning Deep Learning, - Classification, Pytorch <br>
18 - Beginning Deep Learning, - Classification - regression - MIMO - Functional API Tensorflow <br> 
19 - Beginning Deep Learning, - Convolution Networks - Tensorflow <br>
20 - Beginning Deep Learning, - Convolution Networks, PyTorch <br>
21 - Beginning Regularization - Early Stopping, Dropout, L2 (Ridge), L1 (Lasso) <br>
23 - Beginning Model TFServing <br>

But conn.log is not the only file within Zeek. Let's build some models for DNS and HTTP logs. <br>
I choose unsupervised, because there are no labels coming with these data. <br>

24 - Continuing Anomaly Learning - Zeek DNS Log - Machine Learning <br>
25 - Continuing Unsupervised Learning - Zeek HTTP Log - Machine Learning <br> <br>

This was a specific ask by someone in one of my class. <br>
26 - Beginning - Reading Executables and Building a Neural Network to make predictions on suspicious vs suspicious  <br><br>

With 26 notebooks in this series, it is quite possible there are things I could have or should have done differently.  <br>
If you find any thing, you think fits those criteria, drop me a line. <br>

In [1]:
# Import the torch library
import torch

In [2]:
# Similar to Tensorflow - see 
#       02 - Beginning Tensorflow  
# PyTorch is a deep learning library

In [3]:
# First up, PyTorch is a deep learning framework
# While Numpy as seen in notebook 
#   01 - Beginning Numpy
# cannot be used with GPU, PyTorch can
# The system this is being developed on does not have a GPU
# Confirming the devices currently available and we see CUDA is not available
torch.cuda.is_available()

False

In [4]:
# Setup an integer Tensor array with 1 item
x = torch.tensor([10])
x

tensor([10])

In [5]:
# Get the datetype of x
x.dtype

torch.int64

In [6]:
# Confirm the type is of tensor
type(x)

torch.Tensor

In [7]:
# Because no GPU is available, by default everything is placed on the CPU
x.device

device(type='cpu')

In [8]:
# Setup the tensor with multiple integer items
x = torch.tensor([10, 20, 30])
x

tensor([10, 20, 30])

In [9]:
# Setup the tensor with multiple float items
x = torch.tensor([10., 20., 30.])
x, x.dtype


(tensor([10., 20., 30.]), torch.float32)

In [10]:
# Alternatively, cast the multiple item tensor from integer to float
x = torch.tensor([10, 20, 30], dtype=torch.float32)
x

tensor([10., 20., 30.])

In [11]:
# Add a new dimension to the tensor
# Make it a 2 dimension tensor
# Notice the additional "[" and "]"
x = torch.tensor([[10, 20, 30]], dtype=torch.float32)
x

tensor([[10., 20., 30.]])

In [12]:
# We can also add a new dimension by unsqueezing axis 1
# This also moves the x above from 2 to 3 dimensions
x.unsqueeze(dim=1)

tensor([[[10., 20., 30.]]])

In [13]:
# Alternatively, we can manually create a tensor of 3 dimensions
x = torch.tensor([[[10, 20, 30]]], dtype=torch.float32)
x

tensor([[[10., 20., 30.]]])

In [14]:
# Reshape the x tensor
# In this case, (-1, 1) means any amount of rows but only one column
# For this scenario, since x is 1 row and 3 columns, this transitions it to 3 rows and 1 column
# Notice the transition from 1 to 2 dimensions
x = torch.tensor([[[10, 20, 30]]], dtype=torch.float32).reshape(-1,1)
x


tensor([[10.],
        [20.],
        [30.]])

In [15]:
# Like the unsqueezing above, we can squeeze also
# In this case, we move x from a 3x1 shape to a vector of shape 3
# Notice above we have 3 rows now we have 1
x.squeeze(dim=1), x.squeeze(dim=1).shape

(tensor([10., 20., 30.]), torch.Size([3]))

In [16]:
# Reshape the x tensor
# In this case, (-1, 1) means any amount of rows but only one column
# For this scenario, since x is 1 row and 3 columns, this keeps it to 3 rows and 1 column
# Notice the transition from 1 to 2 dimensions
x = torch.tensor([[[10, 20, 30]]], dtype=torch.float32).reshape(1,-1)
x


tensor([[10., 20., 30.]])

In [17]:
# Create two tensors to stack
# Notice, in this case, unlike Numpy and Tensorflow, I created these tensors with 2 dimensions
#   01 - Beginning Numpy
#   02 - Beginning Tensorflow
x = torch.tensor([[1, 2, 3, 4, 5]], dtype=torch.float32)
y = torch.tensor([[6, 7, 8, 9, 0]], dtype=torch.float32)

x, y

(tensor([[1., 2., 3., 4., 5.]]), tensor([[6., 7., 8., 9., 0.]]))

In [18]:
# Stack x and y vertically. Going down the columns, i.e. axis=0
# Note this needs to be a list/array of items
# This is very helpful, if you would like to stack two datasets to create 1
z = torch.cat((x, y), dim=0)
z

tensor([[1., 2., 3., 4., 5.],
        [6., 7., 8., 9., 0.]])

In [19]:
# Similar to numpy vstack, we can use vstack in PyTorch
#      01 - Beginning Numpy
z = torch.vstack((x, y))
z

tensor([[1., 2., 3., 4., 5.],
        [6., 7., 8., 9., 0.]])

In [20]:
# Stack x and y across the columns, i.e. axis=1
# Note this needs to be a tuple of items
# This is helpful when you want to add new features to your dataset
z = torch.cat((x, y), dim=1)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9., 0.]])

In [21]:
# We could also use torch.hstack here
# Horizontal stack
# This allows us to stack across axis=1
z = torch.hstack((x, y))
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9., 0.]])

In [22]:
# Find the offset within x where the value equals 4
x = torch.tensor([10, 9, 8, 7, 6, 5, 4], dtype=torch.float32)
z = torch.where((x == 5))
z

(tensor([5]),)

In [23]:
# Confirming the return positioned 
x[5]

tensor(5.)

In [24]:
# Generate a 4*4 tensor of ones
torch.ones((4,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [25]:
# Create a 6x6 tensor with all zeros
x = torch.zeros((6,6))
x

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [26]:
# Update the item at position row 0, column 0 with 2
# Counting for both the rows and columns start 0
# As a result, even though this tensor is 6x6, you 
# will be going from 0 to 5 for the indexes
x[0,0] = 2
x

tensor([[2., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [27]:
# Update the items at position row 3, column 5 with 100
x[3,5] = 100
x


tensor([[  2.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0., 100.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.]])

In [28]:
# Maybe instead, manipulate columns 1, 2 and 3 of the last row. 
# Remember, the last row is row 5
# We can do x[5, 1:4] = 23 
# or
x[-1, 1:4] = 23

# you might notice below, while we specified 1:4, we only were able to update up to index position 3 
x

tensor([[  2.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0., 100.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,  23.,  23.,  23.,   0.,   0.]])

In [29]:
# One more. Change the values from the last to the second column
# Giving them a value of -10
x[1, -5:] = -10
x

tensor([[  2.,   0.,   0.,   0.,   0.,   0.],
        [  0., -10., -10., -10., -10., -10.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,   0.,   0.,   0.,   0., 100.],
        [  0.,   0.,   0.,   0.,   0.,   0.],
        [  0.,  23.,  23.,  23.,   0.,   0.]])

In [30]:
# Get the max value of all the items in the tensor
torch.max(x)

tensor(100.)

In [31]:
# Get the max value in the tensor going down the columns 
# Going across axis=0
# Notice torch returns the values as well as its index
torch.max(x, axis=0)

torch.return_types.max(
values=tensor([  2.,  23.,  23.,  23.,   0., 100.]),
indices=tensor([0, 5, 5, 5, 0, 3]))

In [32]:
# Get the max value in the tensor across each row
# Notice torch returns the values as well as its index
torch.max(x, axis=1)

torch.return_types.max(
values=tensor([  2.,   0.,   0., 100.,   0.,  23.]),
indices=tensor([0, 0, 0, 5, 0, 1]))

In [33]:
# Create an array to be transposed
x = torch.tensor([[10, 9, 8, 7, 5]])
x

tensor([[10,  9,  8,  7,  5]])

In [34]:
# Use the full transpose function to change from a row vector to a column vector
x.transpose(-2, 1)

tensor([[10],
        [ 9],
        [ 8],
        [ 7],
        [ 5]])

In [35]:
# Maybe you like the shorter way to transpose
# simply use .T on the array
x.T

tensor([[10],
        [ 9],
        [ 8],
        [ 7],
        [ 5]])

In [36]:
# Create a 4 * 4 eye tensor
# Notice all the ones on the diagonal
# This is helpful also when you think about one-hot encoding
x = torch.eye(n=4, m=4, dtype=torch.float32)
x

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [37]:
# Preparing to do some math
# Define a tensor with axes 0 and 1
x = torch.tensor([[6,4,3], [9, 8, 0]])
x

tensor([[6, 4, 3],
        [9, 8, 0]])

In [38]:
# Get the sum of x
x_sum = torch.sum(x)
x_sum

tensor(30)

In [39]:
# Rather than get the sum of the entire tensor, 
# Get the sum going across  the rows, i.e axis=1
x_sum = torch.sum(x, axis=1)
x_sum

tensor([13, 17])

In [40]:
# Similarly get the sum  going down the columns, i.e axis=0
x_sum = torch.sum(x, axis=0)
x_sum

tensor([15, 12,  3])

In [41]:
# Get the average going down the columns, axes=1
# Notice I had to cast x's datatype from integer to float
# if not, the returned average is an integer rather than a float
x_avg = torch.mean(x.type(torch.float32), dim=1)
x_avg

tensor([4.3333, 5.6667])

In [42]:
# Get the average of going across the rows, axes=1
# Notice I had to cast x's datatype from integer to float
# If not, the returned average is an integer rather than a float
x_avg = torch.mean(x.type(torch.float32), dim=0)
x_avg

tensor([7.5000, 6.0000, 1.5000])

In [43]:
# Generate a random number between 10 and 20
# Because I would like a scalar output, the size is empty
# Scalar being a single value or rank 0 tensor
torch.randint(low=10, high=20, size=())

tensor(14)

In [44]:
# You may have instances you wish to generate the same random number
# Maybe for demonstration purposes. Like in this notebook :-) 
# In this case, first set the random seed

for idx, value in enumerate(range(5)):
    # Set the random seed
    torch.random.manual_seed(10)

    # Generate the number
    print(f'Run: {idx} \t value: {torch.randint(low=10, high=20, size=())}')

Run: 0 	 value: 17
Run: 1 	 value: 17
Run: 2 	 value: 17
Run: 3 	 value: 17
Run: 4 	 value: 17


In [45]:
# In looking for max values, you might instead want the index of that value
# This is beneficial when dealing with Softmax activation functions in your neural networks output layer
# The output below has '1' which means the max value is at index position 1. 
# Counting from 0, we see 10 in position 1
x = torch.tensor([2, 10,5,2,3], dtype=torch.int32)
torch.argmax(x), x

(tensor(1), tensor([ 2, 10,  5,  2,  3], dtype=torch.int32))

In [46]:
# Multiply two tensor
# First create the matrices 
x = torch.tensor([[2,3,4]], dtype=torch.int32)
y = torch.tensor([[5],[4],[3]], dtype=torch.int32)
x, y

(tensor([[2, 3, 4]], dtype=torch.int32),
 tensor([[5],
         [4],
         [3]], dtype=torch.int32))

In [47]:
# Remember, if we are going to perform the dot product on two tensors
# We need to ensure the inner dimension has to be the same
# let's confirm the shape of these two tensors
# We get 3,3 for the inner dimensions
x.shape, y.shape

(torch.Size([1, 3]), torch.Size([3, 1]))

In [48]:
# Get the dot product of the two vectors
# Note the need to go across dimension 1
torch.tensordot(a=x, b=y, dims=1)

tensor([[34]], dtype=torch.int32)

In [49]:
# Alternatively, perform a pairwise or Hadamar product
torch.multiply(input=x, other=y)

tensor([[10, 15, 20],
        [ 8, 12, 16],
        [ 6,  9, 12]], dtype=torch.int32)

In [50]:
# Get the cumulative sum of the vector
x

tensor([[2, 3, 4]], dtype=torch.int32)

In [51]:
# Get the cumulative sum
# Notice how the first value in x remains the same, then the first and second are added
# Then the second and third are added
torch.cumsum(x, dim=1)

tensor([[2, 5, 9]])

In [52]:
# Do the same for dimension 0. 
# Note no changes to x
torch.cumsum(x, dim=0)

tensor([[2, 3, 4]])

In [53]:
# Create x with 4 dimensions
x = torch.tensor([[[[2,3,4,5,6]]]])
x, 'Dimensions:', x.ndim

(tensor([[[[2, 3, 4, 5, 6]]]]), 'Dimensions:', 4)

In [54]:
# Flatten x to a vector
# Using two different methods
# This is very helpful when moving from, for example a convolution network to a dense network
#   19 - Beginning Deep Learning, - Convolution Networks - Tensorflow
#   20 - Beginning Deep Learning, - Convolution Networks, PyTorch
x.flatten(), torch.flatten(x)

(tensor([2, 3, 4, 5, 6]), tensor([2, 3, 4, 5, 6]))

In [55]:
# Alternatively, we could have used torch.ravel() to get a 1D array
x, torch.ravel(x)

(tensor([[[[2, 3, 4, 5, 6]]]]), tensor([2, 3, 4, 5, 6]))

In [56]:
# Maybe Just squeeze
x.squeeze()

tensor([2, 3, 4, 5, 6])

In [57]:
# Create a 2*3 tensor
x = torch.tensor([[3,4,5], [6,7,8]])
x, x.shape

(tensor([[3, 4, 5],
         [6, 7, 8]]),
 torch.Size([2, 3]))

In [58]:
# Delete the last column from x
t = x
t[..., 0:2]

tensor([[3, 4],
        [6, 7]])

In [59]:
# Delete the last two column from x
# https://stackoverflow.com/questions/62372762/delete-an-element-from-torch-tensor
t = x
t[..., 0:1]

tensor([[3],
        [6]])

In [60]:
# Delete the last row from x
t = x
t[0:1, ...]

tensor([[3, 4, 5]])

In [61]:
# One more before moving on, broadcasting
# Taking a 2x3 tensor and multiple by a 1*3 vector
# https://numpy.org/doc/stable/user/basics.broadcasting.html
torch.multiply(torch.tensor([[10,2,3], [2,1,3]]), torch.tensor([4,5,6]))

tensor([[40, 10, 18],
        [ 8,  5, 18]])

In [62]:
# The above is the same as multiplying 
# [[10,2,3],   * [[4,5,6]
# [2,1,3]]        [4,5,6]]
torch.multiply(torch.tensor([[10,2,3], [2,1,3]]), torch.tensor([[4,5,6], [4,5,6]]))

tensor([[40, 10, 18],
        [ 8,  5, 18]])

In [63]:
# Maybe we want to save our Torch tensor
torch.save(obj=x, f='x-tensor.pt')

In [64]:
# Verify the file has been saved
!dir /b x-tensor.pt

x-tensor.pt


In [65]:
# load the saved tensor
torch.load(f='x-tensor.pt')

tensor([[3, 4, 5],
        [6, 7, 8]])

In [66]:
# Thats' it

References:<br>
https://pytorch.org/docs/stable/index.html <br>
https://pytorch.org/docs/stable/tensors.html <br>
https://medium.com/@schartz/the-shape-of-tensor-bab75001d7bc <br>
https://pytorch.org/docs/stable/generated/torch.cat.html <br>
https://pytorch.org/docs/stable/generated/torch.eye.html <br>
https://pytorch.org/docs/stable/generated/torch.randint.html <br>
https://www.tensorflow.org/guide/tensor <br>